// Generated by LiveScript 1.2.0
(function(){
  var express, app, path;
  express = require('express');
  app = express();
  path = require('path');
  app.use(express['static'](path.join(__dirname, 'static')));
  app.listen(8080);
  console.log('Listening on port 8080');
}).call(this);
