// Generated by LiveScript 1.2.0
(function(){
  var root;
  root = typeof exports != 'undefined' && exports !== null ? exports : this;
  $(document).ready(function(){
    console.log('hello!');
    return $('#foo').text('javascript working');
  });
}).call(this);
